name: build site

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: build
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install
          yarn build

      - name: git
        if: ${{ !env.ACT }}
        run: bash .github/scripts/git-push-if-changes.sh
