name: build site

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NVM
        run: |
          export HD=$(pwd)
          cd ~
          rm -rf .nvm
          git clone https://github.com/nvm-sh/nvm.git .nvm
          cd ~/.nvm
          git checkout v0.39.4
          . ./nvm.sh
          echo "export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion" >> ~/.bashrc
          nvm install 18
          nvm use 18
          cd $HD
          npm -v
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install
          yarn build

      - name: git status
        run: git status

      - name: git
        if: ${{ !env.ACT }}
        run: bash .github/scripts/git-push-if-changes.sh
